package model;
// Generated Aug 22, 2017 9:17:06 AM by Hibernate Tools 5.2.3.Final


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import model.Books;


/**
 * Author generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "AUTHOR")
public class Author implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8065160113905852337L;
	
	private int authorid;
	private Users users;
	private String authorname;
	private boolean isASubscriber = false;
	private AuthorFiles profile;
	private Subscriber subscriber;
	//private Set<Message> messages = new HashSet<Message>(0);
	private Set<Subscriber> subscribers = new HashSet<Subscriber>(0);
	 @Transient
    private List<Link> links = new ArrayList<>();
	
	 @Transient
	 private List<Books> book = new ArrayList<>();
	 @Transient
	 private List<Message> messages = new ArrayList<>();	 

	public Author() {
	}

	public Author(int authorid) {
		this.authorid = authorid;
	}

	public Author(int authorid, Users users, String authorname) {
		this.authorid = authorid;
		this.users = users;
		this.authorname = authorname;
		
	}

	


	public Author(int authorid, String authorname, boolean isASubscriber, AuthorFiles profile, Subscriber subscriber,
			List<Link> links, List<Books> book, List<Message> messages) {
		super();
		this.authorid = authorid;
		this.authorname = authorname;
		this.isASubscriber = isASubscriber;
		this.profile = profile;
		this.subscriber = subscriber;
		this.links = links;
		this.book = book;
		this.messages = messages;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AUTHOR_SEQ")
	@SequenceGenerator(name="AUTHOR_SEQ", sequenceName="AUTHOR_SEQ", allocationSize=1)
	@Column(name = "AUTHORID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getAuthorid() {
		return this.authorid;
	}

	public void setAuthorid(int authorid) {
		this.authorid = authorid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID")
	@XmlTransient
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "AUTHORNAME", length = 50)
	public String getAuthorname() {
		return this.authorname;
	}

	public void setAuthorname(String authorname) {
		this.authorname = authorname;
	}
	@Transient
	public boolean isASubscriber() {
		return isASubscriber;
	}

	public void setASubscriber(boolean isASubscriber) {
		this.isASubscriber = isASubscriber;
	}

	
	@XmlTransient
	@OneToMany(mappedBy = "author")
	public Set<Subscriber> getSubscribers() {
		return this.subscribers;
	}

	public void setSubscribers(Set<Subscriber> subscribers) {
		this.subscribers = subscribers;
	}
	
	@Transient
	 public List<Books> getBook() {
		return book;
	}
   
	public void setBook(List<Books> book) {
		this.book = book;
	}
	
	@Transient
	public List<Message> getMessages() {
		return messages;
	}

	public void setMessages(List<Message> messages) {
		this.messages = messages;
	}

	@Transient
	public Subscriber getSubscription() {
		return subscriber;
	}

	public void setSubscription(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@Transient
	public void addLink(String url, String rel){
		Link link = new Link();
		link.setLink(url);
		link.setRel(rel);
		links.add(link);
	}
	

	@Transient
	public List<Link> getLinks() {
		return links;
	}
	 @Transient
	public void setLinks(List<Link> links) {
		this.links = links;
	}
	
	
	@XmlTransient
	@OneToOne(mappedBy = "author")
	public AuthorFiles getProfile() {
		return profile;
	}

	public void setProfile(AuthorFiles profile) {
		this.profile = profile;
	}

	@Override
	public String toString() {
		return "Author [authorid=" + authorid + ", authorname=" + authorname + "]";
	}

	

}
