package model;
// Generated Sep 7, 2017 10:11:05 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * AuthorFiles generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "AUTHOR_FILES")
public class AuthorFiles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Author author;
	private byte[] portrait;
	
	

	public AuthorFiles() {
	}

	public AuthorFiles(int id) {
		this.id = id;
	}

	public AuthorFiles(int id, byte[] portrait) {
		super();
		this.id = id;
		this.portrait = portrait;
		
	}

	public AuthorFiles(int id, Author author, byte[] portrait) {
		this.id = id;
		this.author = author;
		this.portrait = portrait;
		
		
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AUTHOR_FILES_SEQ")
	@SequenceGenerator(name="AUTHOR_FILES_SEQ", sequenceName="AUTHOR_FILES_SEQ", allocationSize=1)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	@XmlTransient
	@OneToOne
	@JoinColumn(name = "AUTHORID")
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}
	
	
	@Column(name = "PORTRAIT")
	public byte[] getPortrait() {
		return this.portrait;
	}

	public void setPortrait(byte[] portrait) {
		this.portrait = portrait;
	}

	
	
	@Override
	public String toString() {
		return "AuthorFiles [id=" + id + ", author=" + author + "]";
	}
    
}
