package model;
// Generated Aug 22, 2017 9:17:06 AM by Hibernate Tools 5.2.3.Final

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "MESSAGE")
@XmlRootElement
public class Message implements java.io.Serializable {

	private static final long serialVersionUID = -5522065105669739936L;
	private int messageid;
	private Author author;
	private int authorId;
	private String content;
	private String messageAuthor;
	private String toAuthor;
	private LocalDate datecreated;

	public Message() {
	}

	public Message(int messageid) {
		this.messageid = messageid;
	}

	public Message(int messageid, Author author, String content, LocalDate datecreated) {
		this.messageid = messageid;
		this.author = author;
		this.content = content;
		this.datecreated = datecreated;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "MESSAGE_SEQ")
	@SequenceGenerator(name = "MESSAGE_SEQ", sequenceName = "MESSAGE_SEQ", allocationSize = 1)
	@Column(name = "MESSAGEID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getMessageid() {
		return this.messageid;
	}

	public void setMessageid(int messageid) {
		this.messageid = messageid;
	}

	@XmlTransient
	@ManyToOne
	@JoinColumn(name = "AUTHORID")
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@Column(name = "CONTENT", length = 250)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@XmlTransient
	@Column(name = "DATECREATED")
	public LocalDate getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(LocalDate datecreated) {
		this.datecreated = LocalDate.now();
	}

	@Column(name = "MESSAGEAUTHOR", length = 30)
	public String getMessageAuthor() {
		return messageAuthor;
	}

	public void setMessageAuthor(String messageAuthor) {
		this.messageAuthor = messageAuthor;
	}

	@Transient
	public int getAuthorId() {
		return authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	@Transient
	public String getToAuthor() {
		return toAuthor;
	}

	public void setToAuthor(String toAuthor) {
		this.toAuthor = toAuthor;
	}

}
