package model;
// Generated Aug 22, 2017 9:17:06 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Subscriber generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIBER")
@XmlRootElement
public class Subscriber implements java.io.Serializable {

	private static final long serialVersionUID = 2862022781755045233L;
	private int subcriberid;
	private Users users;
	private Author author;
	private String subscribername;

	public Subscriber() {
	}

	public Subscriber(int subcriberid) {
		this.subcriberid = subcriberid;
	}
    
	public Subscriber(int subcriberid, String subscribername) {
		super();
		this.subcriberid = subcriberid;
		this.subscribername = subscribername;
	}

	public Subscriber(int subcriberid, Users users, Author author, String subscribername) {
		this.subcriberid = subcriberid;
		this.users = users;
		this.author = author;
		this.subscribername = subscribername;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SUBSCRIBER_SEQ")
	@SequenceGenerator(name="SUBSCRIBER_SEQ", sequenceName="SUBSCRIBER_SEQ", allocationSize=1)
	@Column(name = "SUBCRIBERID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getSubcriberid() {
		return this.subcriberid;
	}

	public void setSubcriberid(int subcriberid) {
		this.subcriberid = subcriberid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID")
	@XmlTransient
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne
	@JoinColumn(name = "AUTHORID")
	@XmlTransient
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@Column(name = "SUBSCRIBERNAME", length = 50)
	public String getSubscribername() {
		return this.subscribername;
	}

	public void setSubscribername(String subscribername) {
		this.subscribername = subscribername;
	}

}
